apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helloworld-task
  namespace: tekton-pipelines
  labels:
    app: helloworld-maven
spec:
  inputs:
    resources:
      - name: helloworld
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/helloworld/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/helloworld
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: get-dockerfile
      image: alpine:3.8
      workingDir: /workspace/helloworld
      command:
        - /bin/sh
      args:
        - -c
        - "wget -O Dockerfile http://jx.fileserver.fccs.cn/files/dockerfiles/helloworld-maven"
    - name: mvn-package
      image: jxregistry.docker.fccs.cn:28888/zj/tekton/maven-executor:3.5.4-0
      workingDir: /workspace/helloworld
      command:
        - mvn
      args:
        - clean
        - package
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
        - --insecure
        - --insecure-pull
    - name: helm-install
      image: jxregistry.docker.fccs.cn:28888/zj/tekton/kubectl-helm-executor:1.0.0
      env:
        - name: "HELM_HOME"
          value: "/root/.helm"
      command:
      - /bin/sh
      args:
      - -c
      - "helm repo update && helm install --name helloworld-maven --namespace default --set image.tag=1.0.0 chartmuseum/helloworld-maven"