FROM debian:stretch-slim

USER root

RUN apt-get update  
RUN apt-get install -y ca-certificates

RUN mkdir -p /tmp/.kube

COPY helm /usr/local/bin/
COPY kubectl /usr/local/bin/

COPY kubeconfig/jx/ /tmp/.kube/

RUN helm init --client-only && \
    helm repo remove stable local && \
    helm repo add chartmuseum http://172.16.151.114:8088 
